// Architecture rules enforced via arch-unit-ts.
// Generated by the /setup-arch-unit skill. Edit freely — this is a starting point.
//
// Run: npm run test:arch
//
// Rule pattern:
//   classes() | noClasses()
//     .that()...                       // which classes does the rule apply to?
//     .should()... | .should().not()...
//     .dependOnClassesThat()... | .onlyDependOnClassesThat()...
//     .because('<rationale>')
//     .check(project.allClasses());

import { describe, expect, it } from 'vitest';
import { classes, noClasses } from 'arch-unit-ts/dist/main';
import { TypeScriptProject } from 'arch-unit-ts/dist/arch-unit/core/domain/TypeScriptProject';
import { RelativePath } from 'arch-unit-ts/dist/arch-unit/core/domain/RelativePath';

// {{SRC_ROOT}} is filled by the skill based on whether the project uses src/.
const project = new TypeScriptProject(RelativePath.of('{{SRC_ROOT}}'));

describe('Architecture', () => {
  // ─────────────────────────────────────────────────────────────────────
  // Rule 1 — Shared modules must not depend on the routing layer.
  // The app/ directory depends on shared code (components, lib, hooks,
  // utils, ui). Shared code must remain route-agnostic so it can be
  // reused across route groups, contexts, and pages.
  // ─────────────────────────────────────────────────────────────────────
  it('shared code must not depend on app/', () => {
    // Sanity check: at least one of the shared packages must contain files.
    // If this fails, the SHARED_PACKAGES list below is stale relative to the project.
    const sharedClasses = project.allClasses().filter(c => {
      const path = c.packagePath.getDotsPath();
      return {{SHARED_SANITY_PREDICATE}};
    });
    expect(
      sharedClasses.length,
      'sanity: at least one shared module must exist for this rule to be meaningful',
    ).toBeGreaterThan(0);

    noClasses()
      .that()
      .resideInAnyPackage({{SHARED_PACKAGES}})
      .should()
      .dependOnClassesThat()
      .resideInAPackage('..app..')
      .because('app/ may depend on shared code, but shared code must remain route-agnostic')
      .check(project.allClasses());
  });

  // ─────────────────────────────────────────────────────────────────────
  // Rule 2 (opt-in) — Route groups must not cross-import.
  //
  // Route groups like app/(marketing) and app/(shop) exist to separate
  // site sections by team/intent (see Next.js docs: "Route groups are
  // useful for organizing routes by site section, intent, or team").
  // Cross-imports defeat that boundary.
  //
  // CAVEAT — PARENS IN PACKAGE MATCHERS:
  // arch-unit-ts uses dot-path matchers like '..foo..'. Parentheses in
  // folder names may or may not match cleanly. The sanity check below
  // catches the silent zero-match case. If it trips, switch to the
  // manual fallback at the bottom of this file.
  //
  // To enable: uncomment the block below, then duplicate the test for
  // each pair of route groups you want to keep isolated.
  // ─────────────────────────────────────────────────────────────────────
  // it('app/(GROUP_A) must not import from app/(GROUP_B)', () => {
  //   const fromClasses = project.allClasses().filter(c =>
  //     c.packagePath.getDotsPath().includes('(GROUP_A)'),
  //   );
  //   expect(
  //     fromClasses.length,
  //     'sanity: (GROUP_A) route group should contain files — if 0, check the parens caveat',
  //   ).toBeGreaterThan(0);
  //
  //   noClasses()
  //     .that()
  //     .resideInAPackage('..(GROUP_A)..')
  //     .should()
  //     .dependOnClassesThat()
  //     .resideInAPackage('..(GROUP_B)..')
  //     .because('Route groups exist to keep site sections isolated')
  //     .check(project.allClasses());
  // });

  // ─────────────────────────────────────────────────────────────────────
  // Rule 3 (opt-in) — Private folders are implementation details.
  //
  // The Next.js docs state private folders (prefixed `_`) "indicate the
  // folder is a private implementation detail". They should only be
  // imported from within their parent route segment.
  //
  // Same parens-style caveat applies — leading underscores in dot-path
  // segments may not match the way you expect. Verify on first run.
  // ─────────────────────────────────────────────────────────────────────
  // it('files outside app/SEGMENT must not import from app/SEGMENT/_internal', () => {
  //   noClasses()
  //     .that()
  //     .resideOutsideOfPackage('..SEGMENT..')
  //     .should()
  //     .dependOnClassesThat()
  //     .resideInAPackage('..SEGMENT._internal..')
  //     .because('Private folders are implementation details of their parent segment')
  //     .check(project.allClasses());
  // });

  // ─────────────────────────────────────────────────────────────────────
  // Rule 4 (opt-in) — Layered / hexagonal architecture.
  //
  // Uncomment if your codebase organizes code into domain / application /
  // infrastructure layers (DDD, hexagonal architecture, ports & adapters).
  // The Next.js framework itself is unopinionated about this — only enable
  // if your team has committed to a layered structure.
  // ─────────────────────────────────────────────────────────────────────
  // it('domain layer must not depend on application or infrastructure', () => {
  //   classes()
  //     .that()
  //     .resideInAPackage('..domain..')
  //     .should()
  //     .onlyDependOnClassesThat()
  //     .resideInAnyPackage('..domain..')
  //     .because('Domain is the innermost layer — it knows nothing about outer layers')
  //     .check(project.allClasses());
  // });
  //
  // it('application layer must not depend on infrastructure', () => {
  //   noClasses()
  //     .that()
  //     .resideInAPackage('..application..')
  //     .should()
  //     .dependOnClassesThat()
  //     .resideInAnyPackage('..infrastructure..')
  //     .because('Application orchestrates the domain; infrastructure plugs in via ports')
  //     .check(project.allClasses());
  // });
});

// ─────────────────────────────────────────────────────────────────────
// MANUAL FALLBACK
//
// If a sanity check above fails because arch-unit-ts's dot-path matcher
// doesn't handle parens or underscores in folder names, swap the rule
// for a manual check using filterClasses() + a hand-rolled assertion.
//
// Example skeleton — adapt to your route groups:
//
//   it('app/(marketing) must not import from app/(shop)', () => {
//     const marketingClasses = project.filterClasses('app/(marketing)/**/*.{ts,tsx}');
//     expect(marketingClasses.length, 'sanity: glob should match files').toBeGreaterThan(0);
//
//     // hasImport() checks whether a class imports a given name. Substring vs.
//     // exact-identifier semantics may vary — verify with a known-violating file.
//     const violations = marketingClasses.filter(c => c.hasImport('(shop)'));
//
//     expect(
//       violations.map(c => c.packagePath.getDotsPath()),
//       'route group (marketing) must not import from (shop)',
//     ).toEqual([]);
//   });
// ─────────────────────────────────────────────────────────────────────
